.github/workflows/documentation.yml
.github/workflows/documentation_li.yml
CNAME
README.md
docs/source/developer_notes/class_hierarchy.rst
docs/source/developer_notes/lightrag_design_philosophy.rst
lightrag/README.md
lightrag/lightrag/__init__.py
lightrag/pyproject.toml

* documentation workflow will not remove the customize domain
* update the design principles

[minor fix]

---

lightrag/lightrag/components/agent/__init__.py

This repo is to test the ReadTheDocs deployment

ReadTheDocs Test

---

use_cases/simple_qa_anthropic.py

Modified `preset_prompt_kwargs` to `prompt_kwargs` in order to clear TypeError: unexpected keyword argument.

Modified simple_qa_anthropic example

---

.github/workflows/documentation.yml
README.md
developer_notes/logging_config.py
docs/source/developer_notes/logging.rst
docs/source/index.rst
lightrag/CHANGELOG.md
lightrag/lightrag/components/model_client/anthropic_client.py
lightrag/lightrag/core/default_prompt_template.py
lightrag/lightrag/core/generator.py
lightrag/lightrag/utils/logger.py
lightrag/pyproject.toml

[Documentation] logging + readme

---

lightrag/lightrag/components/data_process/text_splitter.py
lightrag/tests/test_text_splitter.py

I updated the error raising, please merge.

[A quick update of the text splitter]

---

lightrag/lightrag/components/data_process/data_components.py

chore: update data_components.py

---

docs/source/developer_notes/component.rst
docs/source/get_started/installation.rst

Just fixing a spelling error :)

fix: spelling error

---

.github/workflows/documentation.yml
README.md
docs/source/apis/components/index.rst
docs/source/index.rst
docs/source/tutorials/agent.rst
docs/source/tutorials/component.rst
docs/source/tutorials/generator.rst
docs/source/tutorials/index.rst
docs/source/tutorials/retriever.rst
lightrag/CHANGELOG.md
lightrag/README.md
lightrag/lightrag/core/container.py

Beta iteration [first round documents]

---

lightrag/lightrag/components/model_client/ollama_client.py

#132 - Improved the documentation via the docstrings in the ollama_client file.
- Added explanation based on the documentation via the Ollama github.
- Added references to lower level API.

Update Ollama documentation

---

.github/workflows/documentation.yml

fix missing docs: https://github.com/SylphAI-Inc/AdalFlow/issues/143

[WIP] Fix the doc missing

---

lightrag/lightrag/components/model_client/ollama_client.py
lightrag/lightrag/core/generator.py

we cant put the yield and return in the same function

quick fix on the streaming and nonstreaming

---

lightrag/lightrag/core/component.py
lightrag/lightrag/core/prompt_builder.py

Minor fix of python doc issue.

[MINOR] Minor fix of python doc

---

adalflow/CHANGELOG.md
adalflow/adalflow/__init__.py
adalflow/poetry.lock
adalflow/pyproject.toml
docs/source/get_started/installation.rst
docs/source/index.rst
docs/source/tutorials/agent.rst
docs/source/tutorials/base_data_class.rst
docs/source/tutorials/component.rst
docs/source/tutorials/db.rst
docs/source/tutorials/embedder.rst
docs/source/tutorials/evaluation.rst
docs/source/tutorials/generator.rst
docs/source/tutorials/index.rst
docs/source/tutorials/logging.rst
docs/source/tutorials/logging_tracing.rst
docs/source/tutorials/model_client.rst
docs/source/tutorials/output_parsers.rst
docs/source/tutorials/prompt.rst
docs/source/tutorials/retriever.rst
docs/source/tutorials/text_splitter.rst
docs/source/tutorials/tool_helper.rst

updated the lightrag to adalflow in the tutorials

---

use_cases/generator/basic.ipynb

- Fixes import issues
- sets up environment
- Fixes adalflow import instead of lightrag for groq example
I have tested it with both openai and groq apis its working fine

Update generator usage notebook in usecases

---

use_cases/generator/intermediate.ipynb
use_cases/question_answering/simple_qa.ipynb

This fixes 
- generator - intermediate notebook - update logger with adalflow, use setup_env to initalize
- question_answering - qa notebook - use setup_env to initalize-

Fixes in usage notebooks

---

.github/ISSUE_TEMPLATE/1_bug_report.yaml
.github/ISSUE_TEMPLATE/2_suggest_improvement.yaml
.github/ISSUE_TEMPLATE/4_documenting.yaml
.github/ISSUE_TEMPLATE/5_suggest_integration.yaml
.github/ISSUE_TEMPLATE/6_suggest_usecases_benchmarks.yaml
README.md

Additionally optimize the issue templates.

[readme] Add quick start

---

docs/source/contributor/index.rst

Make the contributor message more clear.
<details>
</details>

improve the contributor message

---

docs/source/contributor/index.rst

Merge the following pr to release doc:
https://github.com/SylphAI-Inc/AdalFlow/pull/275 
<details>
</details>

 [release] doc

---

docs/source/get_started/installation.rst

Just minor doc correction.
Fixes #\<issue_number>
<details>
</details>

[MINOR] Rename lightrag to adalflow in doc

---

adalflow/adalflow/components/output_parsers/outputs.py
adalflow/adalflow/core/__init__.py
adalflow/adalflow/core/default_prompt_template.py
adalflow/adalflow/core/generator.py
adalflow/adalflow/core/model_client.py
adalflow/adalflow/core/prompt_builder.py
docs/source/tutorials/generator.rst
docs/source/tutorials/prompt.rst

Just rename from lightrag to adalflow in some python code and docs.
Fixes #\<issue_number>
<details>
</details>

[MINOR] Rename from lightrag to adalflow

---

docs/pyproject.toml

fix the empty package

---

adalflow/adalflow/components/retriever/lancedb_retriver.py
docs/source/tutorials/retriever.rst
notebooks/tutorials/adalflow_classification_optimization.ipynb
tutorials/retriever/adalflow_lancedb.py

test lance db

---

adalflow/CHANGELOG.md
adalflow/adalflow/core/generator.py
adalflow/adalflow/datasets/__init__.py
adalflow/adalflow/datasets/gsm8k.py
adalflow/adalflow/datasets/types.py
adalflow/adalflow/optim/parameter.py
adalflow/adalflow/optim/trainer/trainer.py
docs/source/index.rst
docs/source/new_tutorials/embedder.rst
use_cases/question_answering/gsm8k/task.py
use_cases/question_answering/gsm8k/train.py

add gsm8k dataset

---

adalflow/adalflow/components/output_parsers/dataclass_parser.py
adalflow/adalflow/core/base_data_class.py

Title self explanatory. Each commit message describes individual changes in more detail

Grammar and spelling fixes

---

docs/source/tutorials/text_splitter.rst

Small PR - Commit 9f62a9acf095cb98c738aa9171d9d8e977226627 moved the `adalflow_text_splitter.py` tutorial. This PR adjusts sources to changes.
<details>
</details>

update text splitter source

---

docs/source/tutorials/evaluation.rst

Fix a typo of optimizinh to optimizing
Fixes #\<issue_number>
<details>
</details>

Fix Typo in Documentation

---

docs/source/index.rst
docs/source/new_tutorials/core_concepts.rst

Text/Doc spelling/typo fixes only
N/A
<details>
- Was this **discussed/agreed** via a GitHub issue? No, only doc/text changes
- Did you make sure to **update the documentation** with your changes? N/A - Doc change
- Did you write any **new necessary tests**? No - Doc change
- Did you list all the **breaking changes** introduced by this pull request? N/A
</details>

Just a couple of tiny text/doc spelling/typo fixes.

---

adalflow/adalflow/apps/permission_manager.py
adalflow/adalflow/components/agent/runner.py
adalflow/adalflow/components/memory/memory.py
adalflow/adalflow/core/func_tool.py
adalflow/adalflow/core/tool_manager.py
adalflow/adalflow/core/types.py

three main changes: add confirmation details and pre_execute_callback like display the diff render for file editing, (2) add status for tooloutput (3) refactored the runnder streaming code to incoporate the callback

[tool call optimization]

---

adalflow/adalflow/components/retriever/faiss_retriever.py
use_cases/rag/build/rag.py
use_cases/rag/rag_with_eval.py

Fixes #\443>
<details>
-- Yes, this fixes issue #443 which was reported by @StoneWillow
--   Yes, followed the contribution guidelines
--  Yes, this PR focuses solely on fixing the IndexError crash in rag_with_eval.py
-- No documentation updates needed for this bug fix
-- No new tests needed - this fixes existing functionality
-- all tests pass locally
-- No breaking changes - this is a backward-compatible bug fix
</details>

fixed wrong import, method call signature, empty list checks
